# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            inar1.github.io
tagline:          ""
description:      ""
url:              https://inar1.github.io/
baseurl:          https://inar1.github.io/
imageurl:         https://media.githubusercontent.com/media/inar1/inar1.github.io/master/public/images/
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           inari
  url:            https://github.com/inar1
paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/inar1

google_analytics: UA-135458812-1
